name: CI
on: ["push", "pull_request"]

jobs:
  build:
    name: test python scripts.
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v3
      - name: Actualizar python a la ultima version.
        uses: actions/setup-python@v4 
        with:
          python-version: 3.10.4
      - name: Setear directorio de trabajo.
        run: |
          composer install --no-scripts
        working-directory: ./tests
      - name: Instalar dependencias.
        run: |
          python -m pip install --upgrade pip
          pip install -r requerimientos_cicd.txt
          pip install pytest
          
      - name: Testeo scripts.
        run: pytest -v
